version: '3.4'

services:
  nwo_owmservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "29000:29000"
    
    deploy:
      resources:
        limits:
          cpus: '0.1'
        reservations:
          cpus: '0.02'