version: '3.4'

services:
  nwo_owmservice:
    image: nwoowmservice:dev
    container_name: NWO_OWMservice_1
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "NWO_OWMservice"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\sunk0\source\repos\NWO_OWMservice\NWO_OWMservice:/app
      - C:\Users\sunk0\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\sunk0\.nuget\packages\:/root/.nuget/packages:ro
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/NWO_OWMservice.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true